apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: apiserver
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
