apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ceph-volume-provider-system

namePrefix: ceph-volume-provider-

resources:
- ../manager
- ../poollet-rbac
