---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broker-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims/status
  verbs:
  - get
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
