---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ceph.rook.io
  resources:
  - cephobjectstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims/status
  verbs:
  - get
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - bucketclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - bucketpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - bucketpools/finalizers
  verbs:
  - update
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - bucketpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
