---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.ironcore.dev
  resources:
  - volumeclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.ironcore.dev
  resources:
  - volumepools
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.ironcore.dev
  resources:
  - volumepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.ironcore.dev
  resources:
  - volumes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.ironcore.dev
  resources:
  - volumes/finalizers
  verbs:
  - update
- apiGroups:
  - storage.ironcore.dev
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
