apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-script-runner
  namespace: rook-ceph
  labels:
    app: rook-direct-mount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration-script
  template:
    metadata:
      labels:
        app: migration-script
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: rook-direct-mount
          image: mtr.devops.telekom.de/osc/onmetal/cephlet:migration
          command:
            - tail
            - -f
            - /dev/null
          imagePullPolicy: Always
          tty: true
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: KUBECONFIG
              value: /migration/kubeconfig
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /dev
              name: dev
            - mountPath: /sys/bus
              name: sysbus
            - mountPath: /lib/modules
              name: libmodules
            - name: mon-endpoint-volume
              mountPath: /etc/rook
            - name: ceph-admin-secret
              mountPath: /var/lib/rook-ceph-mon
            - name: migration-config
              mountPath: /migration
              readOnly: true
      # if hostNetwork: false, the "rbd map" command hangs, see https://github.com/rook/rook/issues/2021
      hostNetwork: true
      volumes:
        - name: ceph-admin-secret
          secret:
            secretName: rook-ceph-mon
            optional: false
            items:
              - key: ceph-secret
                path: secret.keyring
        - name: dev
          hostPath:
            path: /dev
        - name: sysbus
          hostPath:
            path: /sys/bus
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
              - key: data
                path: mon-endpoints
        - name: migration-config
          secret:
            secretName: migration-config
