---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ori-volume-role
rules:
  - apiGroups:
      - storage.api.onmetal.de
    resources:
      - volumeclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.api.onmetal.de
    resources:
      - volumepools
    verbs:
      - get
      - list
      - watch
