apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-mon-endpoints-reader
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - rook-ceph-mon-endpoints
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
